// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Lang.MacroProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.Lang.MacroProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FSharp.Lang.MacroProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Lang.MacroProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Lang.MacroProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FSharp.Lang.MacroProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
